name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.8.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.8.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        args: run python -m pytest tests

    - name: Build
      uses: abatilo/actions-poetry@v1.8.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        args: build

    - name: Publish
      uses: abatilo/actions-poetry@v1.8.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        args: publish
        env:
          - POETRY_PYPI_TOKEN_PYPI=${{ secrets.PYPI_TOKEN }}
